kind: Secret
apiVersion: v1
metadata:
  name: {{ (datasource "config").name }}
  namespace: kube-system
  labels:
    app: haystack
type: Opaque
data:
  ssl.crt: {{ (datasource "config").cert }}
  ssl.key: {{ (datasource "config").key }}
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ (datasource "config").name }}
  namespace: {{ (datasource "config").namespace }}
  labels:
    app: haystack
type: Opaque
data:
  ssl.crt: {{ (datasource "config").cert }}
  ssl.key: {{ (datasource "config").key }}