#
#  Copyright 2018 Expedia, Inc.
#
#       Licensed under the Apache License, Version 2.0 (the "License");
#       you may not use this file except in compliance with the License.
#      You may obtain a copy of the License at
#
#           http://www.apache.org/licenses/LICENSE-2.0
#
#       Unless required by applicable law or agreed to in writing, software
#       distributed under the License is distributed on an "AS IS" BASIS,
#       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#       See the License for the specific language governing permissions and
#       limitations under the License.
#
version: "3"
services:
  node-finder:
    image: expediadotcom/haystack-service-graph-node-finder:1.0.17
    environment:
      JAVA_XMS: 128m
      HAYSTACK_GRAPHITE_ENABLED: "false"
      HAYSTACK_PROP_KAFKA_NODE_METADATA_TOPIC_PARTITION_COUNT: "1"
      HAYSTACK_PROP_KAFKA_NODE_METADATA_TOPIC_REPLICATION_FACTOR: "1"
    depends_on:
      - "kafkasvc"
    entrypoint: ["/dockerize","-wait=tcp://kafkasvc:9092","-timeout=200s","-wait-retry-interval=40s","--","./start-app.sh"]
    restart: always

  graph-builder:
      image: expediadotcom/haystack-service-graph-graph-builder:1.0.17
      environment:
        JAVA_XMS: 128m
        HAYSTACK_GRAPHITE_ENABLED: "false"
        HAYSTACK_PROP_SERVICE_HTTP_PORT: "8091"
        HAYSTACK_PROP_KAFKA_STREAMS_REPLICATION_FACTOR: 1
      depends_on:
        - "kafkasvc"
      entrypoint: ["/dockerize","-wait=tcp://kafkasvc:9092","-timeout=200s","-wait-retry-interval=40s","--","./start-app.sh"]
      restart: always
      ports:
        - "8091:8091"

  ui:
    environment:
      HAYSTACK_OVERRIDES_CONFIG_PATH: /data/connectors.json
      HAYSTACK_PROP_CONNECTORS_SERVICE__GRAPH_CONNECTOR__NAME: "haystack"
      HAYSTACK_PROP_CONNECTORS_SERVICE__GRAPH_WINDOW__SIZE__IN__SECS: 3600
      HAYSTACK_PROP_CONNECTORS_SERVICE__GRAPH_SERVICE__GRAPH__URL: "http://graph-builder:8091/servicegraph"
