variable "kops_executable_name" {}
variable "k8s_version" {}
variable "k8s_cluster_name" {}
variable "s3_bucket_name" {}
variable "aws_zone" {}
variable "aws_vpc_id" {}
variable "app-nodes_instance_type" {}
variable "app-nodes_instance_count" {}
variable "monitoring-nodes_instance_type" {}
variable "monitoring-nodes_instance_count" {}
variable "masters_instance_type" {}
variable "aws_hosted_zone_id" {}
variable "aws_nodes_subnet" {}
variable "aws_utilities_subnet" {}
