variable "kops_executable_name" {}
variable "k8s_version" {}
variable "k8s_cluster_name" {}
variable "k8s_s3_bucket_name" {}
variable "k8s_aws_zone" {}
variable "k8s_aws_vpc_id" {}
variable "k8s_node_instance_type" {}
variable "k8s_node_instance_count" {}
variable "k8s_master_instance_type" {}
variable "k8s_hosted_zone_id" {}
variable "k8s_aws_nodes_subnet" {}
variable "k8s_aws_utilities_subnet" {}
