language: node_js

node_js:
  - '8'

env:
  global:
  - GH_REF: github.com/ExpediaDotCom/haystack
  - secure: d1SaRc6QGa/eXgUVt+wIb/jqL4gbW2YSVuMJXtx8/XvM1+B0Udl33cXV7XtkK2A6f9jiY/lwv3Sjai3uc3P8+ng53Sit1qw9oM5106sL1YLrccE8omeyjprjLMwv7mAltx6HjyOZ7rb8UZCSa/+QQdZsRrKhlhBS1kdeDOmVfWlCiQk2aCMUtXzSYaBNrilHhszA+aMaea4C+2DmwieHrvpDplNud5eoH60gb7m+AJAKucz0zmCQb8XCB2AErh4yjDHZ+/CV/kGxlWywgppGCwgspmRONQW7eQOGDYg7RkgvsjHVEDyIjWSgHKFhVAR+XxsQJ16jkpZCrljUyGdyVPwpPxUfLU9WvECIjw87q8mkCSPGQQ+7xYpIXbzV7RWLx8LNbt9zqJjGDH6G2rg3OHBbZTT/I43BGmctDmB6MS+OREqo3WrRMovimQimaSDHp3Aa5pF6P0m+3V6yQ5OkDmRAb5EvoT4XW+0I5p0+DwPZ09o6Mlr8StrcEWO2TWMpQLBSoroUqM+aoMo9RZrc5r2i/BsHQ+WnsZ+veofIzFLFtqbnVlLgOSZiBBuKqOn5A7ZmQcvsfIkHA4FNOD9MWURaeNC/GEUc2CBH5wV5y0Kcbrz3wJGUBWRurbLaAzX2qdO7HyC1/1GAORM6De8BTFV5VrkPEE+wgWqID2ZGfC4=
  - secure: u7s7D6P+E5XNLY2Vs8EqD/g6ZXZsRCJv+o715CxcwipmSmt/iCQ0qI2Jq2nBjabazT4n/EBIqAMXw4dBVt4I/CoygACIuC4FvJy0nqT1NVyiyp/bHf8vXC2fhNq7vIcJ3OjgzpgssOfmsYVVp0ahOKP7AaUAMO5O/R70XCqba8ZFFsebCGhme19WhbGQ5TB5UtHy/xPeso5p+MgdaKAwiAfVQHP+dbItuTV1C9raD9UJVA+T+B94T6RxIksmtbO3pOOCHOpy6mf93DCwKBhUe7HrHiLuf9bJO8n07DSTwBitWSJR4aB+oKnaWNSrBfI8Y6Vq1A3zIByUPSdrOyBinugJxFCigPGAaOgn2qSteOTS30zqGKsT5HB6yND1jEP0LjjH5pNizqelp6DIkB1qPDsU9e6cGs/z4gl4zl/PsjuoJuVxISXGESgdcYyNagSm3Hi00c8dKEohN3xCZkIWsbjk5ie+W7B9afbHRJHCxI5rY/MDgn+oZGSrdJ63fayJJV5uhcJIupgCqeoTDDk7R1qLJZvEbavCtBMxE5vE7Cqh7iesMMCSQkiNaqySdGSv79piMnVKm9c40MpUAetOHY5qHZ2/CE+UR7ANCzx7io08sKT3vJBcF/Ws5Cu5yTlY+OwVfjAE95hZmmKkkoINq6wpkANsrJVL8zU1maHB9AI=

script:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ];  then docs/deploy_docsite.sh; fi

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: out
  target_branch: gh-pages-shadow
  on:
    branch: travis-for-docs
