language: node_js

node_js:
  - '8'

# generate doc pages resources and move generated resources to out folder
script:
  - cd docs && ./generate_docsite.sh && mv _book ../out

# deploy out folder to gh-pages branch
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: out
  target_branch: gh-pages-shadow
  on:
    branch: travis-for-docs
