language: node_js

node_js:
  - '8'

script:
  - cd docs && ./generate_docsite.sh  # generate doc pages
  - mv docs/_book ../out            # move generated resources to out folder

# deploy out folder to gh-pages branch
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: out
  target_branch: gh-pages-shadow
  on:
    branch: travis-for-docs
