language: node_js

sudo: required

node_js:
  - '8'

env:
  - CHANGE_MINIKUBE_NONE_USER=true
  global:
    - BRANCH=${TRAVIS_BRANCH}
    - TAG=${TRAVIS_TAG}
    - SHA=${TRAVIS_COMMIT}

# Install Minikube on the Travis host where the build will be running
before_script:
  - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.7.0/bin/linux/amd64/kubectl && \
    chmod +x kubectl && sudo mv kubectl /usr/local/bin/
  - curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && \
    chmod +x minikube && sudo mv minikube /usr/local/bin/
  - sudo minikube start --vm-driver=none --kubernetes-version=v1.7.0
  - minikube update-context
  - JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}'; \
    until kubectl get nodes -o jsonpath="$JSONPATH" 2>&1 | grep -q "Ready=True"; do sleep 1; done

# generate doc pages and move generated resources to out folder
script:
  - ./deployment/terraform/apply-compose.sh -r plan
  - git config --global user.email "absrivastava@users.noreply.github.com"
  - git config --global user.name "absrivastava"
  - echo "machine github.com login absrivastava password $GITHUB_TOKEN" > ~/.netrc
  - if ([ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]) || [ -n "$TRAVIS_TAG" ]; then cd ./docsite && GIT_USER=$GITHUB_USER ./generate_docsite.sh; fi

notifications:
  email:
    - haystack-notifications@expedia.com
