language: node_js

node_js:
  - "8"

script:
  # build and publish docsite
  # upload to dockerhub only for master(non PR)
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ];  then docs/deploy_docsite.sh; fi
