language: node_js

node_js:
  - '8'

env:
  global:
  - GH_REF: github.com/ExpediaDotCom/haystack
  - secure: v6nuDXEAuaUAcCgcQK1ll0n0O7NH+TS4sN0v09NY4OLaelsw6NUTIYPz7ak/vhlNGqykMAJcx2iAKF6PCP1Sz31gNJPNS+29gYJhxuXtF2kBAcswT50dQIXpHu2x2swsGRw52sqO+BXLmxqjxpVe59/mlYQUI0ECUWGdLSVJwz75oWpA4i85nVfWjB9i7ncqu6hJ2MWFFZnzRhNvFIndXscswM+/9PKEx5OMi78qEvj3HT1yiu9ooVJ32P1av0DPQXK8ZsLVrBU5O8RNp78M1TqbwLQB38o7mdGftTJB6MjWTuNLzozFZxDM8+ArF0O8Dc6Hm0IEU9AxmfBWXectPANf2FgmQPaCv1VkobT/tDN4ZP110v4xC6m7cN5WT42iwGurkNYPUPNPkBmnFDiKY6YjmUsqYX0y9Ne1BUjQVLH8s+hnm1TACWxI6ut04D+JZRtarWQCB5udrigkBTzcGBeCM4PLjFZ4cC9rychrNmCB64xf9C9nTSs/8SGqnmd9lCG9QnnIlvC5DtREG2oJoKr0iT/35PyohEDwpPeK8lM8B5foneYiRVmdKs4oXU6c75pYVmGSEAcccsoJcqWgUkbygWl+krxaRIHtu+H6xOCQoiah1idtV3v7SztHY5eWDIwCoJujd0JaW8CvPlf9Y+bWxVDK24WUCEnFKLwBtgQ=

script:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ];  then docs/deploy_docsite.sh; fi
