language: node_js

node_js:
  - '8'

env:
  global:
  - GH_REF: github.com/ExpediaDotCom/haystack
  - secure: "d1SaRc6QGa/eXgUVt+wIb/jqL4gbW2YSVuMJXtx8/XvM1+B0Udl33cXV7XtkK2A6f9jiY/lwv3Sjai3uc3P8+ng53Sit1qw9oM5106sL1YLrccE8omeyjprjLMwv7mAltx6HjyOZ7rb8UZCSa/+QQdZsRrKhlhBS1kdeDOmVfWlCiQk2aCMUtXzSYaBNrilHhszA+aMaea4C+2DmwieHrvpDplNud5eoH60gb7m+AJAKucz0zmCQb8XCB2AErh4yjDHZ+/CV/kGxlWywgppGCwgspmRONQW7eQOGDYg7RkgvsjHVEDyIjWSgHKFhVAR+XxsQJ16jkpZCrljUyGdyVPwpPxUfLU9WvECIjw87q8mkCSPGQQ+7xYpIXbzV7RWLx8LNbt9zqJjGDH6G2rg3OHBbZTT/I43BGmctDmB6MS+OREqo3WrRMovimQimaSDHp3Aa5pF6P0m+3V6yQ5OkDmRAb5EvoT4XW+0I5p0+DwPZ09o6Mlr8StrcEWO2TWMpQLBSoroUqM+aoMo9RZrc5r2i/BsHQ+WnsZ+veofIzFLFtqbnVlLgOSZiBBuKqOn5A7ZmQcvsfIkHA4FNOD9MWURaeNC/GEUc2CBH5wV5y0Kcbrz3wJGUBWRurbLaAzX2qdO7HyC1/1GAORM6De8BTFV5VrkPEE+wgWqID2ZGfC4="

script:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ];  then docs/deploy_docsite.sh; fi
