sudo: required
dist: trusty

language: java

jdk:
  - oraclejdk8

services:
  - docker

env:
  global:
    - BRANCH=${TRAVIS_BRANCH}
    - TAG=${TRAVIS_TAG}
    - SHA=${TRAVIS_COMMIT}

cache:
  directories:
    - $HOME/.m2

script:
  # build, create docker image
  # upload to dockerhub only for master(non PR) and tag scenario
  - if ([ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]) || [ -n "$TRAVIS_TAG" ];  then make release; else make all; fi

after_success:
  - bash <(curl -s https://codecov.io/bash) || echo 'Codecov failed to upload'

notifications:
  email:
    - haystack-notifications@expedia.com
