language: java

cache:
  directories:
    - $HOME/.m2

install:
  - java -XX:+PrintFlagsFinal -version
  - ./mvnw --version

script:
  # build and deploy if master branch else just build
  - if ([ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]) || [ -n "$TRAVIS_TAG" ]; then .travis/deploy.sh; else ./mvnw clean compile scoverage:report; fi


jdk: openjdk8

notifications:
  email:
    - haystack-notifications@expedia.com
