variable "s3_bucket_name" {}
variable "aws_vpc_id" {}
variable "aws_nodes_subnet" {}
variable "aws_utilities_subnet" {}
variable "aws_hosted_zone_id" {}
variable "aws_ssh_key" {}
variable "haystack_index_store_es_master_instance_type" {}
variable "haystack_index_store_worker_instance_type" {}
variable "haystack_index_store_instance_count" {}
variable "haystack_index_store_master_count" {}
variable "kafka_broker_count" {}
variable "kafka_broker_volume_size" {}
variable "kafka_broker_instance_type" {}
variable "cassandra_node_image" {}
variable "cassandra_node_volume_size" {}
variable "cassandra_seed_node_instance_count" {}
variable "cassandra_non_seed_node_instance_count" {}
variable "cassandra_node_instance_type" {}
variable "k8s_app_name_space" {}
variable "haystack_cluster_name" {}
variable "graphite_hostname" {}
variable "graphite_port" {}

