module "pipes-json-transformer" {
  source = "pipes-json-transformer"
  image = "expediadotcom/haystack-pipes-json-transformer:${var.pipes["version"]}"
  replicas = "${var.pipes["json_transformer_instances"]}"
  namespace = "${var.app_namespace}"
  kafka_hostname = "${var.kafka_hostname}"
  graphite_hostname = "${var.graphite_hostname}"
  graphite_port = "${var.graphite_port}"
  node_selecter_label = "${var.node_selector_label}"
  enabled = "${var.pipes["json_transformer_enabled"]}"
  kubectl_executable_name = "${var.kubectl_executable_name}"
  kubectl_context_name = "${var.kubectl_context_name}"
  cpu_limit = "${var.default_cpu_limit}"
  memory_limit = "${var.default_memory_limit}"
  env_vars = "${var.pipes["json_transformer_environment_overrides"]}"

}

module "pipes-kafka-producer" {
  source = "pipes-kafka-producer"
  image = "expediadotcom/haystack-pipes-kafka-producer:${var.pipes["version"]}"
  replicas = "${var.pipes["kafka_producer_instances"]}"
  namespace = "${var.app_namespace}"
  kafka_hostname = "${var.kafka_hostname}"
  graphite_hostname = "${var.graphite_hostname}"
  graphite_port = "${var.graphite_port}"
  node_selecter_label = "${var.node_selector_label}"
  enabled = "${var.pipes["kafka_producer_enabled"]}"
  kubectl_executable_name = "${var.kubectl_executable_name}"
  kubectl_context_name = "${var.kubectl_context_name}"
  cpu_limit = "${var.default_cpu_limit}"
  memory_limit = "${var.default_memory_limit}"
  env_vars = "${var.pipes["kafka_producer_environment_overrides"]}"

}

module "pipes-http-poster" {
  source = "pipes-http-poster"
  image = "expediadotcom/haystack-pipes-http-poster:${var.pipes["version"]}"
  replicas = "${var.pipes["http_poster_instances"]}"
  namespace = "${var.app_namespace}"
  kafka_hostname = "${var.kafka_hostname}"
  graphite_hostname = "${var.graphite_hostname}"
  graphite_port = "${var.graphite_port}"
  httppost_url = "${var.pipes["http_poster_httppost_url"]}"
  http_poster_httppost_pollpercent = "${var.pipes["http_poster_httppost_pollpercent"]}"

  node_selecter_label = "${var.node_selector_label}"
  enabled = "${var.pipes["http_poster_enabled"]}"
  kubectl_executable_name = "${var.kubectl_executable_name}"
  kubectl_context_name = "${var.kubectl_context_name}"
  cpu_limit = "${var.default_cpu_limit}"
  memory_limit = "${var.default_memory_limit}"
  env_vars = "${var.pipes["http_poster_environment_overrides"]}"
}

module "pipes-firehose-writer" {
  source = "pipes-firehose-writer"
  image = "expediadotcom/haystack-pipes-firehose-writer:${var.pipes["version"]}"
  replicas = "${var.pipes["firehose_writer_instances"]}"
  namespace = "${var.app_namespace}"
  kafka_hostname = "${var.kafka_hostname}"
  graphite_hostname = "${var.graphite_hostname}"
  graphite_port = "${var.graphite_port}"
  firehose_url = "${var.pipes["firehose_writer_firehose_url"]}"
  firehose_streamname = "${var.pipes["firehose_writer_firehose_streamname"]}"
  firehose_kafka_threadcount = "${var.pipes["firehose_kafka_threadcount"]}"
  firehose_signingregion = "${var.pipes["firehose_writer_firehose_signingregion"]}"
  firehose_initialretrysleep = "${var.pipes["firehose_writer_firehose_initialretrysleep"]}"
  firehose_maxretrysleep = "${var.pipes["firehose_writer_firehose_maxretrysleep"]}"
  node_selecter_label = "${var.node_selector_label}"
  enabled = "${var.pipes["firehose_writer_enabled"]}"
  kubectl_executable_name = "${var.kubectl_executable_name}"
  kubectl_context_name = "${var.kubectl_context_name}"
  cpu_limit = "${var.default_cpu_limit}"
  memory_limit = "${var.default_memory_limit}"
  env_vars = "${var.pipes["firehose_writer_environment_overrides"]}"
}

module "pipes-secret-detector" {
  cpu_limit = "${var.default_cpu_limit}"
  enabled = "${var.pipes["secret_detector_enabled"]}"
  env_vars = "${var.pipes["secret_detector_environment_overrides"]}"
  graphite_hostname = "${var.graphite_hostname}"
  graphite_port = "${var.graphite_port}"
  image = "expediadotcom/haystack-pipes-secret-detector:${var.pipes["version"]}"
  kafka_hostname = "${var.kafka_hostname}"
  kubectl_context_name = "${var.kubectl_context_name}"
  kubectl_executable_name = "${var.kubectl_executable_name}"
  memory_limit = "${var.default_memory_limit}"
  namespace = "${var.app_namespace}"
  node_selecter_label = "${var.node_selector_label}"
  pipes_secret_detector_secretsnotifications_email_from = "${var.pipes["secret_detector_secretsnotifications_email_from"]}"
  pipes_secret_detector_secretsnotifications_email_host = "${var.pipes["secret_detector_secretsnotifications_email_host"]}"
  pipes_secret_detector_secretsnotifications_email_subject = "${var.pipes["secret_detector_secretsnotifications_email_subject"]}"
  pipes_secret_detector_secretsnotifications_email_tos = "${var.pipes["secret_detector_secretsnotifications_email_tos"]}"
  replicas = "${var.pipes["secret_detector_instances"]}"
  secret_detector_kafka_threadcount = "${var.pipes["secret_detector_kafka_threadcount"]}"
  source = "pipes-secret-detector"
}
