version: "3"
services:

#  database:
#    image: mysql:5.7
#    ports:
#    - "3306:3306"
#    restart: always
#    volumes:
#      -  ./adaptive-alerting/sql:/home/
#      -  ./adaptive-alerting/db_init:/docker-entrypoint-initdb.d
#    command: --default-authentication-plugin=mysql_native_password
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: aa_model_service
#
#
#  modelservice:
#    image: expediadotcom/adaptive-alerting-modelservice:e90821e5ca0e0d895e01d9cb87612c463dcf0dc6
#    ports:
#    - "8008:8008"
#    environment:
#      AA_GRAPHITE_ENABLED : "false"
#      SPRING_CONFIG_LOCATION : "classpath:/application.yml"
#      PASSWORD : "root"
#      JAVA_XMS: 128m
#    depends_on:
#      - database
#    links:
#      - database
#    restart: always

  modelservice:
    image: rodolpheche/wiremock
#    ports:
#    - "8500:8080"
    volumes:
    - ./adaptive-alerting/stubs:/home/wiremock/


  aa-mapper:
    image: expediadotcom/adaptive-alerting-ad-mapper:e90821e5ca0e0d895e01d9cb87612c463dcf0dc6
    environment:
      AA_GRAPHITE_ENABLED : "false"
      AA_OVERRIDES_CONFIG_PATH : "/home/docker.conf"
      JAVA_XMS: 128m
    volumes:
      - ./adaptive-alerting/configs/aa-mapper:/home
    depends_on:
    - kafkasvc
    - zookeeper
    - modelservice
    links:
    - kafkasvc
    - modelservice
    restart: always

  aa-manager:
    image: expediadotcom/adaptive-alerting-ad-manager:e90821e5ca0e0d895e01d9cb87612c463dcf0dc6
    environment:
      AA_GRAPHITE_ENABLED : "false"
      AA_OVERRIDES_CONFIG_PATH : "/home/docker.conf"
      JAVA_XMS: 128m
    volumes:
      - ./adaptive-alerting/configs/aa-manager:/home
    depends_on:
    - kafkasvc
    - zookeeper
    - modelservice
    links:
    - kafkasvc
    - modelservice
    restart: always

  anomaly-to-alert:
    image: expediadotcom/adaptive-alerting-a2a-mapper:3482d04bcee0c62b1d64e5cf9b289f243d03a77b
    environment:
      AA_GRAPHITE_ENABLED : "false"
      JAVA_XMS: 128m
    depends_on:
    - kafkasvc
    - zookeeper
    links:
    - kafkasvc
    restart: always

  subscription:
    image: expediadotcom/alert-manager-service:67a10b9e28dfc51e806b9ee629ad91a7dfc1d505
    environment:
      AM_GRAPHITE_ENABLED : "false"
      SPRING_CONFIG_LOCATION : "classpath:/application.yml"
      JAVA_XMS: 128m
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    restart: always


# tell about kafka client to read alerts from kafka topic
#  notifier:
#    image: expediadotcom/alert-manager-notifier:3117ece498d619d560939b5acc6bc948b23899da
#    environment:
#      AM_GRAPHITE_ENABLED : "false"
#      SPRING_CONFIG_LOCATION : "classpath:/application.yml"
##       SMTP_PASSWORD: "password"
##       SMTP_USERNAME: "user"
##       SMTP_HOST: "localhost"
##       SLACK_TOKEN: "token"
#      JAVA_XMS: 128m
#    depends_on:
#      - elasticsearch
#      - subscription
#      - zookeeper
#      - kafkasvc
#    links:
#      - elasticsearch
#      - kafkasvc
#      - subscription
#    restart: always


  alert-api:
    image: expediadotcom/haystack-alert-api:f63141bbc1c1e671766b5e83b0e8efb605ab0402
    ports:
    - "4500:8088"
    environment:
      HAYSTACK_GRAPHITE_ENABLED: "false"
      HAYSTACK_LOG_LEVEL: "INFO"
      JAVA_XMS: 128m
    depends_on:
      - elasticsearch
      - subscription
    links:
      - elasticsearch
      - subscription
    restart: always


  anomaly-store:
    image: expediadotcom/haystack-anomaly-store:f63141bbc1c1e671766b5e83b0e8efb605ab0402
    environment:
      HAYSTACK_GRAPHITE_ENABLED: "false"
      HAYSTACK_LOG_LEVEL: "INFO"
      JAVA_XMS: 128m
    depends_on:
      - elasticsearch
      - kafkasvc
    links:
      - kafkasvc
      - elasticsearch
    restart: always


  ui:
    environment:
      HAYSTACK_OVERRIDES_CONFIG_PATH: /data/connectors.json
      HAYSTACK_PROP_CONNECTORS_ALERTS_CONNECTOR__NAME: "haystack"
      HAYSTACK_PROP_CONNECTORS_ALERTS_SUBSCRIPTIONS_CONNECTOR__NAME: "haystack"
      HAYSTACK_PROP_CONNECTORS_ALERTS_HAYSTACK__HOST: "alert-api"
      HAYSTACK_PROP_CONNECTORS_ALERTS_HAYSTACK__PORT: "8088"


