apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: {{ (datasource "config").name }}
  namespace: {{ (datasource "config").namespace }}
spec:
  schedule: "{{ (datasource "config").schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ (datasource "config").name }}
            image:  {{ (datasource "config").image }}
            args:
{{ (datasource "config").args | toYAML | strings.Indent 13 }}
          restartPolicy: OnFailure