/*
 * Copyright 2018 Expedia Group
 *
 *         Licensed under the Apache License, Version 2.0 (the "License");
 *         you may not use this file except in compliance with the License.
 *         You may obtain a copy of the License at
 *
 *             http://www.apache.org/licenses/LICENSE-2.0
 *
 *         Unless required by applicable law or agreed to in writing, software
 *         distributed under the License is distributed on an "AS IS" BASIS,
 *         WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *         See the License for the specific language governing permissions and
 *         limitations under the License.
 */

export default {
    IS_MERGED_SPAN: 'X-HAYSTACK-IS-MERGED-SPAN',
    CLIENT_SERVICE_NAME: 'X-HAYSTACK-CLIENT-SERVICE-NAME',
    CLIENT_OPERATION_NAME: 'X-HAYSTACK-CLIENT-OPERATION-NAME',
    CLIENT_START_TIME: 'X-HAYSTACK-CLIENT-START-TIME',
    CLIENT_DURATION: 'X-HAYSTACK-CLIENT-DURATION',
    CLIENT_SPAN_ID: 'X-HAYSTACK-CLIENT-SPAN-ID',
    IS_AUTOGENERATED_SPAN: 'X-HAYSTACK-AUTOGEN'
};
